---
title: "sentiments"
output: html_document
---
```{r packages, message = FALSE}
library(tidyverse)
library(magrittr) # for %$% operator
library(sentimentr)
library(textclean)


data_dir <- "data"
tweets_dir <- data_dir %>% paste("tweets", sep = "/")
sentiments_dir <- data_dir %>% paste("sentiments", sep = "/")
```


```{r load_tweets}
tweets <- list.files(tweets_dir, full.names = TRUE) %>% 
  map_dfr(read_csv)

prep_tweets <- data_dir %>% paste("prep-tweets.csv", sep = "/") %>% read_csv()

tweets %>% inner_join(prep_tweets) %>% select(c(text, prep_text, emojis))
```


```{r jockers_rinker_sentiments}
jockers_rinker_sentiments <- prep_tweets %>%
  mutate(sentences = get_sentences(prep_text)) %$%  
  sentiment_by(sentences, list(id)) %>% 
  tibble()

file_path <- sentiments_dir %>% paste("jockers-rinker.csv", sep = "/")
jockers_rinker_sentiments %>% write_csv(file_path)

jockers_rinker_sentiments
```


```{r afinn_sentiments}
# Note: download for "afinn" has to be confirmed
hash_sentiment_afinn <- tidytext::get_sentiments("afinn") %>% 
  rename(c(x = word, y = value)) %>% 
  as_key() # convert tibble to data table for sentimentr

afinn_sentiments <- prep_tweets %>% 
  mutate(sentences = get_sentences(prep_text)) %$%
  sentiment_by(sentences, list(id), polarity_dt = hash_sentiment_afinn) %>% 
  tibble()

file_path <- sentiments_dir %>% paste("afinn.csv", sep = "/")
afinn_sentiments %>% write_csv(file_path)

afinn_sentiments
```


```{r nrc_sentients}
nrc_sentiments <- prep_tweets %>% 
  mutate(sentences = get_sentences(prep_text)) %$%
  sentiment_by(sentences, list(id), polarity_dt = lexicon::hash_sentiment_nrc) %>% 
  tibble()

file_path <- sentiments_dir %>% paste("nrc.csv", sep = "/")
nrc_sentiments %>% write_csv(file_path)

nrc_sentiments
```


```{r bing_sentiments}
bing_sentiments <- prep_tweets %>% 
  mutate(sentences = get_sentences(prep_text)) %$%
  sentiment_by(sentences, list(id), polarity_dt = lexicon::hash_sentiment_huliu) %>% 
  tibble()

file_path <- sentiments_dir %>% paste("bing.csv", sep = "/")
bing_sentiments %>% write_csv(file_path)

bing_sentiments
```


```{r novak_emoji_sentiments}
novak_emoji_sentiments <- prep_tweets %>%
  filter(emojis != "") %>% 
  filter(! is.na(emojis)) %>%
  mutate(emojis = replace_emoji_identifier(emojis)) %>% 
  mutate(sentences = get_sentences(emojis)) %$%
  sentiment_by(sentences, list(id), polarity_dt = lexicon::hash_sentiment_emojis) %>% 
  tibble() 

file_path <- sentiments_dir %>% paste("novak-emoji.csv", sep = "/")
novak_emoji_sentiments %>% write_csv(file_path)

novak_emoji_sentiments 
```


```{r load_sentiments}
jockers_rinker <- sentiments_dir %>% 
  paste("jockers-rinker.csv", sep = "/") %>% 
  read_csv() %>% 
  select(c(id, word_count, ave_sentiment)) %>% 
  rename(jockers_rinker = ave_sentiment)

afinn <- sentiments_dir %>% 
  paste("afinn.csv", sep = "/") %>% 
  read_csv() %>% 
  select(c(id, ave_sentiment)) %>% 
  rename(afinn = ave_sentiment)

novak_emoji <- sentiments_dir %>% 
  paste("novak-emoji.csv", sep = "/") %>% 
  read_csv() %>% 
  select(c(id, ave_sentiment)) %>% 
  rename(novak_emoji = ave_sentiment)

nrc <- sentiments_dir %>% 
  paste("nrc.csv", sep = "/") %>% 
  read_csv() %>% 
  select(c(id, ave_sentiment)) %>% 
  rename(nrc = ave_sentiment)

bing <- sentiments_dir %>% 
  paste("bing.csv", sep = "/") %>% 
  read_csv() %>% 
  select(c(id, ave_sentiment)) %>% 
  rename(bing = ave_sentiment)

sentiments <- tweets %>% 
  inner_join(prep_tweets) %>% 
  select(c(id, text, prep_text)) %>% 
  inner_join(jockers_rinker) %>% 
  inner_join(afinn) %>% 
  inner_join(nrc) %>% 
  inner_join(bing) %>% 
  left_join(novak_emoji)

sentiments
```

